version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: citiesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: postgresql://user:password@db:5432/citiesdb
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sleep 10 && python app.py"]  # Задержка перед запуском приложения

volumes:
  postgres_data:
